# Generated by Django 3.1.2 on 2021-09-18 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=5, unique=True)),
                ('filter', models.JSONField(unique=True)),
            ],
        ),
    ]
