# Generated by Django 3.1.2 on 2021-09-20 14:24

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0002_auto_20210920_1423'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='filter',
            name='data_gin',
        ),
        migrations.AddIndex(
            model_name='filter',
            index=django.contrib.postgres.indexes.GinIndex(fields=['filter'], name='filter_gin'),
        ),
    ]
