# Generated by Django 3.1.2 on 2021-08-17 22:08

from django.db import migrations, models
import django.db.models.deletion
import laptop.utils
import laptop.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CpuFamily',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CpuVendor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='GpuVendor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=30)),
                ('cpu_model', models.CharField(max_length=30)),
                ('ram', models.IntegerField()),
                ('hdd', models.IntegerField()),
                ('size', models.FloatField()),
                ('resolution', models.CharField(max_length=12)),
                ('gpu_model', models.CharField(max_length=30)),
                ('weight', models.FloatField()),
                ('image', models.ImageField(upload_to=laptop.utils.handle_upload, validators=[laptop.validators.validate_image_extension])),
                ('cpu_family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laptops', to='offerings.cpufamily', to_field='code')),
                ('gpu_vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laptops', to='offerings.gpuvendor', to_field='code')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('website', models.URLField()),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Scrape',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('total_offerings', models.PositiveIntegerField()),
                ('new_offerings', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=300)),
                ('sku', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('url', models.URLField(unique=True)),
                ('active', models.BooleanField(default=True)),
                ('ignored', models.BooleanField(default=False)),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='offerings.laptop')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='offerings.retailer', to_field='code')),
            ],
        ),
        migrations.AddField(
            model_name='laptop',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laptops', to='offerings.vendor', to_field='code'),
        ),
        migrations.AddField(
            model_name='cpufamily',
            name='cpu_vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpu_families', to='offerings.cpuvendor', to_field='code'),
        ),
        migrations.AddIndex(
            model_name='offering',
            index=models.Index(fields=['price'], name='offerings_o_price_40e59a_idx'),
        ),
        migrations.AddIndex(
            model_name='offering',
            index=models.Index(fields=['active'], name='offerings_o_active_bfcf22_idx'),
        ),
    ]
