# Generated by Django 3.1.2 on 2021-08-17 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailer',
            name='website',
        ),
        migrations.AlterField(
            model_name='offering',
            name='sku',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
