# Generated by Django 3.1.2 on 2021-08-17 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offerings', '0002_auto_20210817_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='cpu_family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laptops', to='offerings.cpufamily', to_field='code'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='gpu_vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laptops', to='offerings.gpuvendor', to_field='code'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='sku',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laptops', to='offerings.vendor', to_field='code'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
