# Generated by Django 3.1.2 on 2021-08-17 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerings', '0005_auto_20210817_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
