# Generated by Django 3.1.2 on 2021-08-24 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offerings', '0011_auto_20210823_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='cpu_family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laptops', to='offerings.cpufamily', to_field='code'),
        ),
    ]
