# Generated by Django 3.1.2 on 2021-09-20 22:55

from django.db import migrations, models
import laptop.utils
import laptop.validators


class Migration(migrations.Migration):

    dependencies = [
        ('offerings', '0012_auto_20210824_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='url',
        ),
        migrations.AlterField(
            model_name='laptop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=laptop.utils.handle_upload, validators=[laptop.validators.validate_image_extension]),
        ),
    ]
